
package cn.tedu.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWSImpl", targetNamespace = "http://ws.tedu.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWSImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws.tedu.cn/", className = "cn.tedu.ws.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws.tedu.cn/", className = "cn.tedu.ws.SayHelloResponse")
    @Action(input = "http://ws.tedu.cn/HelloWSImpl/sayHelloRequest", output = "http://ws.tedu.cn/HelloWSImpl/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "introduce", targetNamespace = "http://ws.tedu.cn/", className = "cn.tedu.ws.Introduce")
    @ResponseWrapper(localName = "introduceResponse", targetNamespace = "http://ws.tedu.cn/", className = "cn.tedu.ws.IntroduceResponse")
    @Action(input = "http://ws.tedu.cn/HelloWSImpl/introduceRequest", output = "http://ws.tedu.cn/HelloWSImpl/introduceResponse")
    public String introduce(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

}
